# AQI Prediction System
## Data Preprocessing & Exploratory Data Analysis(EDA)
Author: Anjali Tiwari

In [9]:
import pandas as pd
print("Pandas imported successfully")

Pandas imported successfully

## Loading Required Libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries loaded successfully ✅")

Libraries loaded successfully ✅

## Reading PDF Dataset

In [11]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully")

Libraries imported successfully

In [12]:
import pdfplumber

pdf_path = "data/prayagraj_air_quality_data (1).pdf"

with pdfplumber.open(pdf_path) as pdf:
    print("Total Pages:", len(pdf.pages))

FileNotFoundError: [Errno 2] No such file or directory: 'data/prayagraj_air_quality_data (1).pdf'

In [ ]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\DELL\AppData\Local\Programs\Python\Python313\python.exe
3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]

In [ ]:
import pdfplumber

print("pdfplumber imported successfully ✅")

pdfplumber imported successfully ✅

## Extracting Tables from PDF

In [ ]:
import pdfplumber

pdf_path = "data/prayagraj_air_quality_data (1).pdf"

all_tables = []

with pdfplumber.open(pdf_path) as pdf:
    print(f"Total Pages: {len(pdf.pages)}")

    for page_num, page in enumerate(pdf.pages):

        table = page.extract_table()

        if table:
            all_tables.append(table)
            print(f"Page {page_num+1}: Table Found ✅")

        else:
            print(f"Page {page_num+1}: No Table ❌")

FileNotFoundError: [Errno 2] No such file or directory: 'data/prayagraj_air_quality_data (1).pdf'

In [ ]:
import os

print(os.getcwd())

e:\OneDrive\Desktop\AQI_Prediction_System\notebooks

In [ ]:
import pdfplumber

pdf_path = "../data/prayagraj_air_quality_data (1).pdf"

all_tables = []

with pdfplumber.open(pdf_path) as pdf:
    print(f"Total Pages: {len(pdf.pages)}")

    for page_num, page in enumerate(pdf.pages):
        table = page.extract_table()

        if table:
            all_tables.append(table)
            print(f"Page {page_num+1}: Table Found ✅")
        else:
            print(f"Page {page_num+1}: No Table ❌")

Total Pages: 6
Page 1: No Table ❌
Page 2: No Table ❌
Page 3: Table Found ✅
Page 4: Table Found ✅
Page 5: Table Found ✅
Page 6: Table Found ✅

## Preview Extracted Tables

In [ ]:
print("Total Tables Extracted:", len(all_tables))

print("\nFirst Table Preview:\n")

for row in all_tables[0][:10]:
    print(row)

Total Tables Extracted: 4

First Table Preview:

['OCTOBER (2015) - DECEMBER (2015)', None, None, None, None, None, None, None]
['', '', None, '', None, '', None, '']
['Air Quality Data', 'Traffic Area', None, 'Industrial Area', None, 'Residential Area', None, 'Green Area']
[None, 'Civil Lines', 'Rambagh', 'Naini', 'Phoolpur', 'Katra', 'Teliyarganj', 'Company Bagh']
['AQI', '228.3', '235.0', '250.0', '260.0', '215.0', '190.0', '120.0']
['PM2.5 (µg/m³)', '125', '130', '140', '145', '118', '105', '60']
['PM10 (µg/m³)', '245', '255', '270', '280', '230', '205', '125']
['NO2 (µg/m³)', '34.7', '36.0', '39.0', '40.0', '32.0', '28.0', '15.0']
['SO2 (µg/m³)', '9.0', '9.0', '10.0', '11.0', '8.0', '7.0', '5.0']
['NH3 (µg/m³)', '31.3', '32.0', '34.0', '36.0', '29.0', '25.0', '15.0']

## Converting Extracted Table into DataFrame

In [13]:
# Convert first extracted table into DataFrame

df = pd.DataFrame(all_tables[0])

print("Shape of DataFrame:", df.shape)

df.head(10)

Shape of DataFrame: (14, 8)

,0,1,2,3,4,5,6,7
0,OCTOBER (2015) - DECEMBER (2015),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,,NaN,,NaN,,NaN,
2,Air Quality Data,Traffic Area,NaN,Industrial Area,NaN,Residential Area,NaN,Green Area
3,NaN,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
4,AQI,228.3,235.0,250.0,260.0,215.0,190.0,120.0
5,PM2.5 (µg/m³),125,130,140,145,118,105,60
6,PM10 (µg/m³),245,255,270,280,230,205,125
7,NO2 (µg/m³),34.7,36.0,39.0,40.0,32.0,28.0,15.0
8,SO2 (µg/m³),9.0,9.0,10.0,11.0,8.0,7.0,5.0
9,NH3 (µg/m³),31.3,32.0,34.0,36.0,29.0,25.0,15.0

## Inspecting Extracted Data

In [14]:
print("Shape :", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

Shape : (14, 8)

Columns:
RangeIndex(start=0, stop=8, step=1)

Data Types:
0    str
1    str
2    str
3    str
4    str
5    str
6    str
7    str
dtype: object

Missing Values:
0    1
1    1
2    3
3    1
4    3
5    1
6    3
7    1
dtype: int64

## Viewing Complete Extracted Table

In [15]:


df

,0,1,2,3,4,5,6,7
0,OCTOBER (2015) - DECEMBER (2015),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,,NaN,,NaN,,NaN,
2,Air Quality Data,Traffic Area,NaN,Industrial Area,NaN,Residential Area,NaN,Green Area
3,NaN,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
4,AQI,228.3,235.0,250.0,260.0,215.0,190.0,120.0
5,PM2.5 (µg/m³),125,130,140,145,118,105,60
6,PM10 (µg/m³),245,255,270,280,230,205,125
7,NO2 (µg/m³),34.7,36.0,39.0,40.0,32.0,28.0,15.0
8,SO2 (µg/m³),9.0,9.0,10.0,11.0,8.0,7.0,5.0
9,NH3 (µg/m³),31.3,32.0,34.0,36.0,29.0,25.0,15.0
10,O3 (µg/m³),18.7,18.0,17.0,16.0,20.0,22.0,28.0
11,Temperature (°C),22.1,22.1,22.1,22.1,22.1,22.1,21.8
12,Humidity (%),73,73,73,73,73,74,80
13,Wind Speed (m/s),1.4,1.4,1.3,1.3,1.5,1.7,2.2

## Inspecting Header Row

In [16]:
df.iloc[3]

0             NaN
1     Civil Lines
2         Rambagh
3           Naini
4        Phoolpur
5           Katra
6     Teliyarganj
7    Company Bagh
Name: 3, dtype: str

## Setting Proper Column Names

In [17]:
df.columns = [
    "Parameter",
    "Civil Lines",
    "Rambagh",
    "Naini",
    "Phoolpur",
    "Katra",
    "Teliyarganj",
    "Company Bagh"
]

print("Column names updated successfully ✅")

Column names updated successfully ✅

In [18]:
df.head()

,Parameter,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
0,OCTOBER (2015) - DECEMBER (2015),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,,NaN,,NaN,,NaN,
2,Air Quality Data,Traffic Area,NaN,Industrial Area,NaN,Residential Area,NaN,Green Area
3,NaN,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
4,AQI,228.3,235.0,250.0,260.0,215.0,190.0,120.0

## Removing Unnecessary Header Rows

In [19]:
# Keep only actual air quality measurements
df_clean = df.iloc[4:].reset_index(drop=True)

print("Cleaned Shape:", df_clean.shape)

df_clean.head()

Cleaned Shape: (10, 8)

,Parameter,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
0,AQI,228.3,235.0,250.0,260.0,215.0,190.0,120.0
1,PM2.5 (µg/m³),125,130,140,145,118,105,60
2,PM10 (µg/m³),245,255,270,280,230,205,125
3,NO2 (µg/m³),34.7,36.0,39.0,40.0,32.0,28.0,15.0
4,SO2 (µg/m³),9.0,9.0,10.0,11.0,8.0,7.0,5.0

## Transposing Dataset

In [20]:
df_final = df_clean.set_index("Parameter").T

df_final

Parameter,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
Civil Lines,228.3,125,245,34.7,9.0,31.3,18.7,22.1,73,1.4
Rambagh,235.0,130,255,36.0,9.0,32.0,18.0,22.1,73,1.4
Naini,250.0,140,270,39.0,10.0,34.0,17.0,22.1,73,1.3
Phoolpur,260.0,145,280,40.0,11.0,36.0,16.0,22.1,73,1.3
Katra,215.0,118,230,32.0,8.0,29.0,20.0,22.1,73,1.5
Teliyarganj,190.0,105,205,28.0,7.0,25.0,22.0,22.1,74,1.7
Company Bagh,120.0,60,125,15.0,5.0,15.0,28.0,21.8,80,2.2

## Resetting Index and Creating Location Column

In [21]:
df_final = df_final.reset_index()

df_final = df_final.rename(columns={"index": "Location"})

df_final.head()

Parameter,Location,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
0,Civil Lines,228.3,125,245,34.7,9.0,31.3,18.7,22.1,73,1.4
1,Rambagh,235.0,130,255,36.0,9.0,32.0,18.0,22.1,73,1.4
2,Naini,250.0,140,270,39.0,10.0,34.0,17.0,22.1,73,1.3
3,Phoolpur,260.0,145,280,40.0,11.0,36.0,16.0,22.1,73,1.3
4,Katra,215.0,118,230,32.0,8.0,29.0,20.0,22.1,73,1.5

In [22]:
df_final.columns

Index(['Location', 'AQI', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO2 (µg/m³)',
       'SO2 (µg/m³)', 'NH3 (µg/m³)', 'O3 (µg/m³)', 'Temperature (°C)',
       'Humidity (%)', 'Wind Speed (m/s)'],
      dtype='str', name='Parameter')

## Checking Final Dataset Information

In [23]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Location          7 non-null      str
 1   AQI               7 non-null      str
 2   PM2.5 (µg/m³)     7 non-null      str
 3   PM10 (µg/m³)      7 non-null      str
 4   NO2 (µg/m³)       7 non-null      str
 5   SO2 (µg/m³)       7 non-null      str
 6   NH3 (µg/m³)       7 non-null      str
 7   O3 (µg/m³)        7 non-null      str
 8   Temperature (°C)  7 non-null      str
 9   Humidity (%)      7 non-null      str
 10  Wind Speed (m/s)  7 non-null      str
dtypes: str(11)
memory usage: 748.0 bytes

## Converting Data Types

In [24]:
# Convert all columns except Location to numeric

numeric_columns = df_final.columns[1:]

df_final[numeric_columns] = df_final[numeric_columns].apply(pd.to_numeric)

print("Data types converted successfully ✅")

Data types converted successfully ✅

In [25]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Location          7 non-null      str
 1   AQI               7 non-null      float64
 2   PM2.5 (µg/m³)     7 non-null      int64
 3   PM10 (µg/m³)      7 non-null      int64
 4   NO2 (µg/m³)       7 non-null      float64
 5   SO2 (µg/m³)       7 non-null      float64
 6   NH3 (µg/m³)       7 non-null      float64
 7   O3 (µg/m³)        7 non-null      float64
 8   Temperature (°C)  7 non-null      float64
 9   Humidity (%)      7 non-null      int64
 10  Wind Speed (m/s)  7 non-null      float64
dtypes: float64(7), int64(3), str(1)
memory usage: 748.0 bytes

## Previewing Second Extracted Table

In [26]:
df2 = pd.DataFrame(all_tables[1])

print("Shape:", df2.shape)

df2.head(10)

Shape: (14, 8)

,0,1,2,3,4,5,6,7
0,JANUARY (2018) - DECEMBER (2018),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,,NaN,,NaN,,NaN,
2,Air Quality Data,Traffic Area,NaN,Industrial Area,NaN,Residential Area,NaN,Green Area
3,NaN,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
4,AQI,225,235,255,265,215,195,130
5,PM2.5 (µg/m³),125,130,145,150,120,105,65
6,PM10 (µg/m³),240,250,280,290,230,205,135
7,NO2 (µg/m³),36,38,41,43,33,29,17
8,SO2 (µg/m³),9,9,10,11,8,7,5
9,NH3 (µg/m³),32,33,36,38,30,26,16

## Cleaning Second Extracted Table

In [27]:
df2 = df2.iloc[4:].reset_index(drop=True)

df2.columns = [
    "Parameter",
    "Civil Lines",
    "Rambagh",
    "Naini",
    "Phoolpur",
    "Katra",
    "Teliyarganj",
    "Company Bagh"
]

df2.head()

,Parameter,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
0,AQI,225,235,255,265,215,195,130
1,PM2.5 (µg/m³),125,130,145,150,120,105,65
2,PM10 (µg/m³),240,250,280,290,230,205,135
3,NO2 (µg/m³),36,38,41,43,33,29,17
4,SO2 (µg/m³),9,9,10,11,8,7,5

In [28]:
df2 = df2.set_index("Parameter").T.reset_index()

df2.rename(columns={"index": "Location"}, inplace=True)

df2.head()

Parameter,Location,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
0,Civil Lines,225,125,240,36,9,32,19,25.3,72,1.5
1,Rambagh,235,130,250,38,9,33,18,25.3,72,1.5
2,Naini,255,145,280,41,10,36,17,25.2,71,1.4
3,Phoolpur,265,150,290,43,11,38,16,25.2,71,1.4
4,Katra,215,120,230,33,8,30,21,25.3,73,1.6

In [29]:
numeric_columns = df2.columns[1:]

df2[numeric_columns] = df2[numeric_columns].apply(pd.to_numeric)

df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Location          7 non-null      str
 1   AQI               7 non-null      int64
 2   PM2.5 (µg/m³)     7 non-null      int64
 3   PM10 (µg/m³)      7 non-null      int64
 4   NO2 (µg/m³)       7 non-null      int64
 5   SO2 (µg/m³)       7 non-null      int64
 6   NH3 (µg/m³)       7 non-null      int64
 7   O3 (µg/m³)        7 non-null      int64
 8   Temperature (°C)  7 non-null      float64
 9   Humidity (%)      7 non-null      int64
 10  Wind Speed (m/s)  7 non-null      float64
dtypes: float64(2), int64(8), str(1)
memory usage: 748.0 bytes

In [30]:
df2.describe()

Parameter,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
count,7.000000,7.00000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,217.142857,120.00000,232.857143,33.857143,8.428571,30.142857,20.428571,25.185714,73.285714,1.628571
std,45.079295,28.57738,51.950068,8.802056,1.988060,7.358183,4.466809,0.146385,3.147183,0.287021
min,130.000000,65.00000,135.000000,17.000000,5.000000,16.000000,16.000000,24.900000,71.000000,1.400000
25%,205.000000,112.50000,217.500000,31.000000,7.500000,28.000000,17.500000,25.150000,71.500000,1.450000
50%,225.000000,125.00000,240.000000,36.000000,9.000000,32.000000,19.000000,25.200000,72.000000,1.500000
75%,245.000000,137.50000,265.000000,39.500000,9.500000,34.500000,22.000000,25.300000,73.500000,1.700000
max,265.000000,150.00000,290.000000,43.000000,11.000000,38.000000,29.000000,25.300000,80.000000,2.200000

## Cleaning Third Extracted Table

In [31]:
df3 = pd.DataFrame(all_tables[2])

print("Shape:", df3.shape)

df3.head(10)

Shape: (14, 8)

,0,1,2,3,4,5,6,7
0,JANUARY (2021) - DECEMBER (2021),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,,NaN,,NaN,,NaN,
2,Air Quality Data,Traffic Area,NaN,Industrial Area,NaN,Residential Area,NaN,Green Area
3,NaN,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
4,AQI,220,230,250,260,210,190,130
5,PM2.5 (µg/m³),125,130,145,150,120,105,70
6,PM10 (µg/m³),240,250,280,290,230,205,135
7,NO2 (µg/m³),36,38,41,43,34,29,17
8,SO2 (µg/m³),9,9,10,11,8,7,5
9,NH3 (µg/m³),32,33,36,38,30,26,17

In [32]:
df3 = df3.iloc[4:].reset_index(drop=True)

df3.columns = [
    "Parameter",
    "Civil Lines",
    "Rambagh",
    "Naini",
    "Phoolpur",
    "Katra",
    "Teliyarganj",
    "Company Bagh"
]

df3.head()

,Parameter,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
0,AQI,220,230,250,260,210,190,130
1,PM2.5 (µg/m³),125,130,145,150,120,105,70
2,PM10 (µg/m³),240,250,280,290,230,205,135
3,NO2 (µg/m³),36,38,41,43,34,29,17
4,SO2 (µg/m³),9,9,10,11,8,7,5

In [33]:
df3 = df3.set_index("Parameter").T.reset_index()

df3.rename(columns={"index": "Location"}, inplace=True)

df3.head()

Parameter,Location,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
0,Civil Lines,220,125,240,36,9,32,18,25.6,72,1.5
1,Rambagh,230,130,250,38,9,33,17,25.6,72,1.5
2,Naini,250,145,280,41,10,36,16,25.5,71,1.4
3,Phoolpur,260,150,290,43,11,38,15,25.5,71,1.4
4,Katra,210,120,230,34,8,30,20,25.6,73,1.6

In [34]:
numeric_columns = df3.columns[1:]

df3[numeric_columns] = df3[numeric_columns].apply(pd.to_numeric)

print("Data types converted successfully ✅")

Data types converted successfully ✅

In [35]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Location          7 non-null      str
 1   AQI               7 non-null      int64
 2   PM2.5 (µg/m³)     7 non-null      int64
 3   PM10 (µg/m³)      7 non-null      int64
 4   NO2 (µg/m³)       7 non-null      int64
 5   SO2 (µg/m³)       7 non-null      int64
 6   NH3 (µg/m³)       7 non-null      int64
 7   O3 (µg/m³)        7 non-null      int64
 8   Temperature (°C)  7 non-null      float64
 9   Humidity (%)      7 non-null      int64
 10  Wind Speed (m/s)  7 non-null      float64
dtypes: float64(2), int64(8), str(1)
memory usage: 748.0 bytes

In [36]:
df3.describe()

Parameter,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,212.857143,120.714286,232.857143,34.000000,8.428571,30.285714,19.428571,25.471429,73.285714,1.614286
std,43.479607,26.992062,51.950068,8.793937,1.988060,7.040698,4.466809,0.179947,3.147183,0.254484
min,130.000000,70.000000,135.000000,17.000000,5.000000,17.000000,15.000000,25.100000,71.000000,1.400000
25%,200.000000,112.500000,217.500000,31.500000,7.500000,28.000000,16.500000,25.450000,71.500000,1.450000
50%,220.000000,125.000000,240.000000,36.000000,9.000000,32.000000,18.000000,25.500000,72.000000,1.500000
75%,240.000000,137.500000,265.000000,39.500000,9.500000,34.500000,21.000000,25.600000,73.500000,1.700000
max,260.000000,150.000000,290.000000,43.000000,11.000000,38.000000,28.000000,25.600000,80.000000,2.100000

## Cleaning Fourth Extracted Table

In [37]:
df4 = pd.DataFrame(all_tables[3])

print("Shape:", df4.shape)

df4.head(10)

Shape: (14, 8)

,0,1,2,3,4,5,6,7
0,JANUARY (2024) - DECEMBER (2024),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,,NaN,,NaN,,NaN,
2,Air Quality Data,Traffic Area,NaN,Industrial Area,NaN,Residential Area,NaN,Green Area
3,NaN,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
4,AQI,235,245,265,275,225,205,140
5,PM2.5 (µg/m³),130,135,150,158,125,110,70
6,PM10 (µg/m³),250,260,290,300,240,210,140
7,NO2 (µg/m³),36,38,42,44,33,29,18
8,SO2 (µg/m³),9,9,10,11,8,7,5
9,NH3 (µg/m³),32,33,37,39,31,27,18

In [38]:
df4 = df4.iloc[4:].reset_index(drop=True)

df4.columns = [
    "Parameter",
    "Civil Lines",
    "Rambagh",
    "Naini",
    "Phoolpur",
    "Katra",
    "Teliyarganj",
    "Company Bagh"
]

df4.head()

,Parameter,Civil Lines,Rambagh,Naini,Phoolpur,Katra,Teliyarganj,Company Bagh
0,AQI,235,245,265,275,225,205,140
1,PM2.5 (µg/m³),130,135,150,158,125,110,70
2,PM10 (µg/m³),250,260,290,300,240,210,140
3,NO2 (µg/m³),36,38,42,44,33,29,18
4,SO2 (µg/m³),9,9,10,11,8,7,5

In [39]:
df4 = df4.set_index("Parameter").T.reset_index()

df4.rename(columns={"index": "Location"}, inplace=True)

df4.head()

Parameter,Location,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
0,Civil Lines,235,130,250,36,9,32,18,26.2,71,1.5
1,Rambagh,245,135,260,38,9,33,17,26.2,71,1.5
2,Naini,265,150,290,42,10,37,16,26.1,70,1.4
3,Phoolpur,275,158,300,44,11,39,15,26.1,70,1.4
4,Katra,225,125,240,33,8,31,20,26.2,72,1.6

In [40]:
numeric_columns = df4.columns[1:]

df4[numeric_columns] = df4[numeric_columns].apply(pd.to_numeric)

print("Data types converted successfully ✅")

df4.info()

Data types converted successfully ✅
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Location          7 non-null      str
 1   AQI               7 non-null      int64
 2   PM2.5 (µg/m³)     7 non-null      int64
 3   PM10 (µg/m³)      7 non-null      int64
 4   NO2 (µg/m³)       7 non-null      int64
 5   SO2 (µg/m³)       7 non-null      int64
 6   NH3 (µg/m³)       7 non-null      int64
 7   O3 (µg/m³)        7 non-null      int64
 8   Temperature (°C)  7 non-null      float64
 9   Humidity (%)      7 non-null      int64
 10  Wind Speed (m/s)  7 non-null      float64
dtypes: float64(2), int64(8), str(1)
memory usage: 748.0 bytes

In [41]:
df4.describe()

Parameter,AQI,PM2.5 (µg/m³),PM10 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),NH3 (µg/m³),O3 (µg/m³),Temperature (°C),Humidity (%),Wind Speed (m/s)
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,227.142857,125.428571,241.428571,34.285714,8.428571,31.000000,19.428571,26.071429,72.285714,1.614286
std,45.079295,29.119622,53.984125,8.807464,1.988060,6.952218,4.466809,0.179947,3.147183,0.254484
min,140.000000,70.000000,140.000000,18.000000,5.000000,18.000000,15.000000,25.700000,70.000000,1.400000
25%,215.000000,117.500000,225.000000,31.000000,7.500000,29.000000,16.500000,26.050000,70.500000,1.450000
50%,235.000000,130.000000,250.000000,36.000000,9.000000,32.000000,18.000000,26.100000,71.000000,1.500000
75%,255.000000,142.500000,275.000000,40.000000,9.500000,35.000000,21.000000,26.200000,72.500000,1.700000
max,275.000000,158.000000,300.000000,44.000000,11.000000,39.000000,28.000000,26.200000,79.000000,2.100000

## Import Required Libraries

In [ ]:
!python -m pip install matplotlib seaborn

Collecting matplotlib
  Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: tzdata in c:\users\dell\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.3 MB 5.1 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.3 MB 5.3 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.3 MB 6.3 MB/s eta 0:00:01
   ---------------------- ----------------- 5.2/9.3 MB 6.6 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.3 MB 6.3 MB/s eta 0:00:01
   ----------------------------- ---------- 6.8/9.3 MB 6.2 MB/s eta 0:00:01
   ------------------------------------- -- 8.7/9.3 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 5.7 MB/s  0:00:01
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ----------------- ---------------------- 1.0/2.3 MB 5.3 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.3 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 2.3/2.3 MB 4.9 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/7.2 MB 5.1 MB/s eta 0:00:02
   ---------- ----------------------------- 1.8/7.2 MB 4.8 MB/s eta 0:00:02
   -------------- ------------------------- 2.6/7.2 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 3.9/7.2 MB 4.7 MB/s eta 0:00:01
   ---------------------------- ----------- 5.2/7.2 MB 4.8 MB/s eta 0:00:01
   ---------------------------------- ----- 6.3/7.2 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 4.9 MB/s  0:00:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/8 [pyparsing]
   ---------------------------------------- 0/8 [pyparsing]
   ---------------------------------------- 0/8 [pyparsing]
   ---------------------------------------- 0/8 [pyparsing]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ---------- ----------------------------- 2/8 [kiwisolver]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   -------------------- ------------------- 4/8 [cycler]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.1 pillow-12.3.0 pyparsing-3.3.2 seaborn-0.13.2

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\DELL\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import sys
print(sys.executable)

c:\Users\DELL\AppData\Local\Programs\Python\Python313\python.exe

In [ ]:
!python -m pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
Using cached numpy-2.5.1-cp313-cp313-win_amd64.whl (12.4 MB)
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\DELL\AppData\Local\Programs\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip